# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\牵引供电-朱明\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 891)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1072, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menuBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveas = QtWidgets.QAction(MainWindow)
        self.actionSaveas.setObjectName("actionSaveas")
        self.actionExamples = QtWidgets.QAction(MainWindow)
        self.actionExamples.setObjectName("actionExamples")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionLinespara = QtWidgets.QAction(MainWindow)
        self.actionLinespara.setObjectName("actionLinespara")
        self.actionHlink = QtWidgets.QAction(MainWindow)
        self.actionHlink.setObjectName("actionHlink")
        self.actionLinespara_2 = QtWidgets.QAction(MainWindow)
        self.actionLinespara_2.setObjectName("actionLinespara_2")
        self.actionHlink_2 = QtWidgets.QAction(MainWindow)
        self.actionHlink_2.setObjectName("actionHlink_2")
        self.actionSetlines = QtWidgets.QAction(MainWindow)
        self.actionSetlines.setObjectName("actionSetlines")
        self.actionLinespara_4 = QtWidgets.QAction(MainWindow)
        self.actionLinespara_4.setObjectName("actionLinespara_4")
        self.actionElementpara = QtWidgets.QAction(MainWindow)
        self.actionElementpara.setObjectName("actionElementpara")
        self.actionM = QtWidgets.QAction(MainWindow)
        self.actionM.setObjectName("actionM")
        self.actionUI = QtWidgets.QAction(MainWindow)
        self.actionUI.setObjectName("actionUI")
        self.actionZ = QtWidgets.QAction(MainWindow)
        self.actionZ.setObjectName("actionZ")
        self.actionXiebo = QtWidgets.QAction(MainWindow)
        self.actionXiebo.setObjectName("actionXiebo")
        self.actionDuodao = QtWidgets.QAction(MainWindow)
        self.actionDuodao.setObjectName("actionDuodao")
        self.actionDaorong = QtWidgets.QAction(MainWindow)
        self.actionDaorong.setObjectName("actionDaorong")
        self.actionZhubianyaqi = QtWidgets.QAction(MainWindow)
        self.actionZhubianyaqi.setObjectName("actionZhubianyaqi")
        self.actionATdaona = QtWidgets.QAction(MainWindow)
        self.actionATdaona.setObjectName("actionATdaona")
        self.actionHengxianglianj = QtWidgets.QAction(MainWindow)
        self.actionHengxianglianj.setObjectName("actionHengxianglianj")
        self.actionGongdianbi_fenduan = QtWidgets.QAction(MainWindow)
        self.actionGongdianbi_fenduan.setObjectName("actionGongdianbi_fenduan")
        self.actionF = QtWidgets.QAction(MainWindow)
        self.actionF.setObjectName("actionF")
        self.actionF_2 = QtWidgets.QAction(MainWindow)
        self.actionF_2.setObjectName("actionF_2")
        self.actionF_3 = QtWidgets.QAction(MainWindow)
        self.actionF_3.setObjectName("actionF_3")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(MainWindow)
        self.action4.setObjectName("action4")
        self.action6 = QtWidgets.QAction(MainWindow)
        self.action6.setObjectName("action6")
        self.action6_2 = QtWidgets.QAction(MainWindow)
        self.action6_2.setObjectName("action6_2")
        self.action7 = QtWidgets.QAction(MainWindow)
        self.action7.setObjectName("action7")
        self.action_source_lines = QtWidgets.QAction(MainWindow)
        self.action_source_lines.setObjectName("action_source_lines")
        self.actionpeizhi = QtWidgets.QAction(MainWindow)
        self.actionpeizhi.setObjectName("actionpeizhi")
        self.actionshuchu = QtWidgets.QAction(MainWindow)
        self.actionshuchu.setObjectName("actionshuchu")
        self.menu.addAction(self.actionNew)
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionSaveas)
        self.menu.addSeparator()
        self.menu.addAction(self.actionExamples)
        self.menu.addSeparator()
        self.menu.addAction(self.actionPrint)
        self.menu.addAction(self.action_source_lines)
        self.menu_2.addAction(self.actionSetlines)
        self.menu_4.addAction(self.actionpeizhi)
        self.menu_3.addAction(self.actionshuchu)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "牵引供电系统计算软件"))
        self.menu.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menu_2.setTitle(_translate("MainWindow", "结构配置"))
        self.menu_4.setTitle(_translate("MainWindow", "计算参数配置"))
        self.menu_3.setTitle(_translate("MainWindow", "结果输出"))
        self.actionNew.setText(_translate("MainWindow", "新建(&N)"))
        self.actionNew.setStatusTip(_translate("MainWindow", "新建文件"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionOpen.setText(_translate("MainWindow", "打开(&O)"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "打开文件"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "保存(&S)"))
        self.actionSave.setStatusTip(_translate("MainWindow", "保存线路设置"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveas.setText(_translate("MainWindow", "另存为(&A)"))
        self.actionExamples.setText(_translate("MainWindow", "示例(&E）"))
        self.actionExamples.setStatusTip(_translate("MainWindow", "线路示例"))
        self.actionExamples.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionPrint.setText(_translate("MainWindow", "打印(&P）"))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionLinespara.setText(_translate("MainWindow", "设置"))
        self.actionLinespara.setStatusTip(_translate("MainWindow", "内部参数设置"))
        self.actionLinespara.setShortcut(_translate("MainWindow", "Ctrl+Alt+S"))
        self.actionHlink.setText(_translate("MainWindow", "横向连接元件"))
        self.actionHlink.setStatusTip(_translate("MainWindow", "横向连接元件参数设置"))
        self.actionHlink.setShortcut(_translate("MainWindow", "Ctrl+Alt+S"))
        self.actionLinespara_2.setText(_translate("MainWindow", "导线参数"))
        self.actionLinespara_2.setStatusTip(_translate("MainWindow", "导线参数设置"))
        self.actionHlink_2.setText(_translate("MainWindow", "横向连接元件参数"))
        self.actionHlink_2.setStatusTip(_translate("MainWindow", "横向连接元件参数设置"))
        self.actionSetlines.setText(_translate("MainWindow", "线路配置"))
        self.actionLinespara_4.setText(_translate("MainWindow", "导线参数"))
        self.actionElementpara.setText(_translate("MainWindow", "横向元件参数"))
        self.actionM.setText(_translate("MainWindow", "大矩阵M"))
        self.actionUI.setText(_translate("MainWindow", "节点电压电流U、I"))
        self.actionZ.setText(_translate("MainWindow", "短路阻抗Z"))
        self.actionXiebo.setText(_translate("MainWindow", "各次谐波"))
        self.actionDuodao.setText(_translate("MainWindow", "多导体阻抗矩阵"))
        self.actionDaorong.setText(_translate("MainWindow", "电容导纳"))
        self.actionZhubianyaqi.setText(_translate("MainWindow", "主变压器导纳矩阵"))
        self.actionATdaona.setText(_translate("MainWindow", "AT导纳矩阵"))
        self.actionHengxianglianj.setText(_translate("MainWindow", "横向连接线矩阵"))
        self.actionGongdianbi_fenduan.setText(_translate("MainWindow", "供电臂分段"))
        self.actionF.setText(_translate("MainWindow", "负荷（机车）导纳矩阵、电流矩阵"))
        self.actionF_2.setText(_translate("MainWindow", "故障（短路）导纳矩阵"))
        self.actionF_3.setText(_translate("MainWindow", "链式网络模型"))
        self.action1.setText(_translate("MainWindow", "接触网电压曲线"))
        self.action2.setText(_translate("MainWindow", "接触网电流曲线"))
        self.action3.setText(_translate("MainWindow", "钢轨电位曲线"))
        self.action4.setText(_translate("MainWindow", "大地回流曲线"))
        self.action6.setText(_translate("MainWindow", "短路阻抗曲线"))
        self.action6_2.setText(_translate("MainWindow", "谐波电压分布曲线"))
        self.action7.setText(_translate("MainWindow", "谐波电流分布曲线"))
        self.action_source_lines.setText(_translate("MainWindow", "原始导线参数管理"))
        self.actionpeizhi.setText(_translate("MainWindow", "配置"))
        self.actionshuchu.setText(_translate("MainWindow", "输出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

