# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Documents\eric6Document\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 891)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1044, 833))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_parameter_tree = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_parameter_tree.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_parameter_tree.setObjectName("widget_parameter_tree")
        self.horizontalLayout.addWidget(self.widget_parameter_tree)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setMinimumSize(QtCore.QSize(200, 200))
        self.widget.setObjectName("widget")
        self.verticalLayout_3.addWidget(self.widget)
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.tab_3)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout.addWidget(self.widget_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.tab_4)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2.addWidget(self.widget_3)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1072, 30))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menuSetpara = QtWidgets.QMenu(self.menu_2)
        self.menuSetpara.setObjectName("menuSetpara")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menuBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveas = QtWidgets.QAction(MainWindow)
        self.actionSaveas.setObjectName("actionSaveas")
        self.actionExamples = QtWidgets.QAction(MainWindow)
        self.actionExamples.setObjectName("actionExamples")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionLinespara = QtWidgets.QAction(MainWindow)
        self.actionLinespara.setObjectName("actionLinespara")
        self.actionHlink = QtWidgets.QAction(MainWindow)
        self.actionHlink.setObjectName("actionHlink")
        self.actionLinespara_2 = QtWidgets.QAction(MainWindow)
        self.actionLinespara_2.setObjectName("actionLinespara_2")
        self.actionHlink_2 = QtWidgets.QAction(MainWindow)
        self.actionHlink_2.setObjectName("actionHlink_2")
        self.actionSetlines = QtWidgets.QAction(MainWindow)
        self.actionSetlines.setObjectName("actionSetlines")
        self.actionLinespara_4 = QtWidgets.QAction(MainWindow)
        self.actionLinespara_4.setObjectName("actionLinespara_4")
        self.actionElementpara = QtWidgets.QAction(MainWindow)
        self.actionElementpara.setObjectName("actionElementpara")
        self.menu.addAction(self.actionNew)
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionSaveas)
        self.menu.addSeparator()
        self.menu.addAction(self.actionExamples)
        self.menu.addSeparator()
        self.menu.addAction(self.actionPrint)
        self.menuSetpara.addAction(self.actionLinespara_4)
        self.menuSetpara.addAction(self.actionElementpara)
        self.menu_2.addAction(self.actionSetlines)
        self.menu_2.addAction(self.menuSetpara.menuAction())
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "牵引供电系统计算软件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        self.menu.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menu_2.setTitle(_translate("MainWindow", "结构配置"))
        self.menuSetpara.setTitle(_translate("MainWindow", "参数"))
        self.menu_4.setTitle(_translate("MainWindow", "运行"))
        self.actionNew.setText(_translate("MainWindow", "新建(&N)"))
        self.actionNew.setStatusTip(_translate("MainWindow", "新建文件"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionOpen.setText(_translate("MainWindow", "打开(&O)"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "打开文件"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "保存(&S)"))
        self.actionSave.setStatusTip(_translate("MainWindow", "保存线路设置"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveas.setText(_translate("MainWindow", "另存为(&A)"))
        self.actionExamples.setText(_translate("MainWindow", "示例(&E）"))
        self.actionExamples.setStatusTip(_translate("MainWindow", "线路示例"))
        self.actionExamples.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionPrint.setText(_translate("MainWindow", "打印(&P）"))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionLinespara.setText(_translate("MainWindow", "设置"))
        self.actionLinespara.setStatusTip(_translate("MainWindow", "内部参数设置"))
        self.actionLinespara.setShortcut(_translate("MainWindow", "Ctrl+Alt+S"))
        self.actionHlink.setText(_translate("MainWindow", "横向连接元件"))
        self.actionHlink.setStatusTip(_translate("MainWindow", "横向连接元件参数设置"))
        self.actionHlink.setShortcut(_translate("MainWindow", "Ctrl+Alt+S"))
        self.actionLinespara_2.setText(_translate("MainWindow", "导线参数"))
        self.actionLinespara_2.setStatusTip(_translate("MainWindow", "导线参数设置"))
        self.actionHlink_2.setText(_translate("MainWindow", "横向连接元件参数"))
        self.actionHlink_2.setStatusTip(_translate("MainWindow", "横向连接元件参数设置"))
        self.actionSetlines.setText(_translate("MainWindow", "线路配置"))
        self.actionLinespara_4.setText(_translate("MainWindow", "导线参数"))
        self.actionElementpara.setText(_translate("MainWindow", "横向元件参数"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

