# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\牵引供电-朱明\setstructure.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(937, 862)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 841, 801))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_basic = QtWidgets.QWidget()
        self.tab_basic.setObjectName("tab_basic")
        self.groupBox = QtWidgets.QGroupBox(self.tab_basic)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 571, 141))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_basic, "")
        self.tab_lines = QtWidgets.QWidget()
        self.tab_lines.setObjectName("tab_lines")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_lines)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget_lines = QtWidgets.QTableWidget(self.tab_lines)
        self.tableWidget_lines.setMinimumSize(QtCore.QSize(320, 0))
        self.tableWidget_lines.setObjectName("tableWidget_lines")
        self.tableWidget_lines.setColumnCount(0)
        self.tableWidget_lines.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget_lines)
        self.widget = QtWidgets.QWidget(self.tab_lines)
        self.widget.setMinimumSize(QtCore.QSize(300, 0))
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 680, 262, 36))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_check = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_check.setObjectName("pushButton_check")
        self.horizontalLayout_2.addWidget(self.pushButton_check)
        spacerItem = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_enter = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_enter.setObjectName("pushButton_enter")
        self.horizontalLayout_2.addWidget(self.pushButton_enter)
        self.layoutWidget.raise_()
        self.tableWidget_lines.raise_()
        self.horizontalLayout.addWidget(self.widget)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_lines, "")
        self.tab_element = QtWidgets.QWidget()
        self.tab_element.setObjectName("tab_element")
        self.tabWidget.addTab(self.tab_element, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "               供电方式"))
        self.radioButton_2.setText(_translate("Form", "AT"))
        self.radioButton.setText(_translate("Form", "直供"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_basic), _translate("Form", "基础"))
        self.pushButton_check.setText(_translate("Form", "查看"))
        self.pushButton_enter.setText(_translate("Form", "确定"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_lines), _translate("Form", "牵引网导线"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_element), _translate("Form", "横向元件"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

