# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Documents\eric6Document\UI_calculator.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(562, 489)
        Dialog.setSizeGripEnabled(True)
        self.lcd = QtWidgets.QLCDNumber(Dialog)
        self.lcd.setGeometry(QtCore.QRect(90, 30, 431, 141))
        self.lcd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd.setDigitCount(8)
        self.lcd.setObjectName("lcd")
        self.b1_13 = QtWidgets.QPushButton(Dialog)
        self.b1_13.setGeometry(QtCore.QRect(690, 400, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b1_13.setFont(font)
        self.b1_13.setObjectName("b1_13")
        self.b1_14 = QtWidgets.QPushButton(Dialog)
        self.b1_14.setGeometry(QtCore.QRect(940, 400, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b1_14.setFont(font)
        self.b1_14.setObjectName("b1_14")
        self.b1_16 = QtWidgets.QPushButton(Dialog)
        self.b1_16.setGeometry(QtCore.QRect(810, 400, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b1_16.setFont(font)
        self.b1_16.setObjectName("b1_16")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(30, 180, 479, 286))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b1 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.horizontalLayout.addWidget(self.b1)
        self.b2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.horizontalLayout.addWidget(self.b2)
        self.b3 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setObjectName("b3")
        self.horizontalLayout.addWidget(self.b3)
        self.b_pluse = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b_pluse.setFont(font)
        self.b_pluse.setObjectName("b_pluse")
        self.horizontalLayout.addWidget(self.b_pluse)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.b4 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setObjectName("b4")
        self.horizontalLayout_2.addWidget(self.b4)
        self.b5 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b5.setFont(font)
        self.b5.setObjectName("b5")
        self.horizontalLayout_2.addWidget(self.b5)
        self.b6 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b6.setFont(font)
        self.b6.setObjectName("b6")
        self.horizontalLayout_2.addWidget(self.b6)
        self.b_sub = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b_sub.setFont(font)
        self.b_sub.setObjectName("b_sub")
        self.horizontalLayout_2.addWidget(self.b_sub)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b7 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b7.setFont(font)
        self.b7.setObjectName("b7")
        self.horizontalLayout_3.addWidget(self.b7)
        self.b8 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b8.setFont(font)
        self.b8.setObjectName("b8")
        self.horizontalLayout_3.addWidget(self.b8)
        self.b9 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b9.setFont(font)
        self.b9.setObjectName("b9")
        self.horizontalLayout_3.addWidget(self.b9)
        self.b_mul = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b_mul.setFont(font)
        self.b_mul.setObjectName("b_mul")
        self.horizontalLayout_3.addWidget(self.b_mul)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b0 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b0.setFont(font)
        self.b0.setObjectName("b0")
        self.horizontalLayout_4.addWidget(self.b0)
        self.b_point = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b_point.setFont(font)
        self.b_point.setObjectName("b_point")
        self.horizontalLayout_4.addWidget(self.b_point)
        self.b_clean = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b_clean.setFont(font)
        self.b_clean.setObjectName("b_clean")
        self.horizontalLayout_4.addWidget(self.b_clean)
        self.b_div = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b_div.setFont(font)
        self.b_div.setObjectName("b_div")
        self.horizontalLayout_4.addWidget(self.b_div)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.b_equ = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b_equ.setFont(font)
        self.b_equ.setObjectName("b_equ")
        self.verticalLayout.addWidget(self.b_equ)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "计算器"))
        Dialog.setWhatsThis(_translate("Dialog", "计算器"))
        self.b1_13.setText(_translate("Dialog", "1"))
        self.b1_14.setText(_translate("Dialog", "1"))
        self.b1_16.setText(_translate("Dialog", "1"))
        self.b1.setText(_translate("Dialog", "1"))
        self.b2.setText(_translate("Dialog", "2"))
        self.b3.setText(_translate("Dialog", "3"))
        self.b_pluse.setText(_translate("Dialog", "+"))
        self.b4.setText(_translate("Dialog", "4"))
        self.b5.setText(_translate("Dialog", "5"))
        self.b6.setText(_translate("Dialog", "6"))
        self.b_sub.setText(_translate("Dialog", "-"))
        self.b7.setText(_translate("Dialog", "7"))
        self.b8.setText(_translate("Dialog", "8"))
        self.b9.setText(_translate("Dialog", "9"))
        self.b_mul.setText(_translate("Dialog", "*"))
        self.b0.setText(_translate("Dialog", "0"))
        self.b_point.setText(_translate("Dialog", "."))
        self.b_clean.setText(_translate("Dialog", "清除"))
        self.b_div.setText(_translate("Dialog", "/"))
        self.b_equ.setText(_translate("Dialog", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

